# Generated by Django 5.0.3 on 2024-04-02 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_ordereditem_size'),
        ('products', '0002_rename_prority_product_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordereditem',
            name='size',
        ),
        migrations.AlterField(
            model_name='ordereditem',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_items', to='products.product'),
        ),
    ]
