# Generated by Django 5.0.3 on 2024-04-03 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='price',
            new_name='total_price',
        ),
    ]
