# Generated by Django 4.1.7 on 2024-04-25 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_rename_quantity_ordereditem_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordereditem',
            name='quantity',
            field=models.IntegerField(default=100),
        ),
    ]
