# Generated by Django 5.0.6 on 2024-05-08 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_owner_app', '0002_rename_name_shopowner_shop_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopowner',
            name='name',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
