# Generated by Django 5.0.3 on 2024-03-21 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.ImageField(upload_to='media/site/')),
                ('caption', models.TextField(max_length=100)),
                ('site_name', models.CharField(max_length=100)),
                ('site_logo', models.ImageField(upload_to='media/images/')),
                ('site_description', models.TextField()),
                ('site_address', models.TextField()),
                ('site_phone', models.CharField(max_length=15)),
                ('site_email', models.EmailField(max_length=254)),
                ('site_fb', models.URLField()),
                ('site_twitter', models.URLField()),
                ('site_instagram', models.URLField()),
                ('site_youtube', models.URLField()),
                ('site_github', models.URLField()),
                ('site_created_at', models.DateTimeField(auto_now_add=True)),
                ('site_updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
