# Generated by Django 5.0.4 on 2024-05-05 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
