# Generated by Django 4.1.7 on 2024-04-25 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_rename_price_order_total_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordereditem',
            old_name='quantity',
            new_name='count',
        ),
    ]
