# Generated by Django 5.0.4 on 2024-05-02 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_productitem_delete_ordereditem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productitem',
            name='price_per_unit',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
