# Generated by Django 5.0.3 on 2024-03-26 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='prority',
            new_name='priority',
        ),
    ]
